# Basic Site Settings
title                    : "Dokka Sai Srikar - Computer Architecture Researcher"
name                     : &name "Dokka Sai Srikar"
description              : &description "Researcher in Computer Architecture, Embedded Systems, and On-Chip Communication"
url                      : "https://saisrikardokka.github.io"
baseurl                  : ""  # Leave blank if deploying directly to GitHub Pages root
repository               : "saisrikardokka/saisrikardokka.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Dokka Sai Srikar"
  pronouns         : "he/him"
  bio              : "Embedded Systems Engineer & Research Intern at IIT Guwahati. Interested in Computer Architecture, Wireless NoC, and EDA."
  location         : "India"
  employer         : "IIT Guwahati"
  email            : "saisrikar.dokka@gmail.com"  # Update if preferred
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "https://orcid.org/0000-0000-0000-0000"  # Replace with your ORCID ID
  github           : "saisrikardokka"
  linkedin         : "dokka-sai-srikar"
  twitter          : "sai_srikar_"  # If you don’t have one, remove it
  researchgate     : # Add if available
  arxiv            : # Add if available

# Social Sharing
twitter:
  username: "sai_srikar_"
social:
  type: "Person"
  name: "Dokka Sai Srikar"
  links:
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - "https://github.com/saisrikardokka"
    - "https://linkedin.com/in/dokka-sai-srikar"
    - "https://orcid.org/0000-0000-0000-0000"  # Replace with actual ORCID
